### ISSUE TITLE
Ubuntu 16.04.2 LTS - ImportError: No module named 'numpy'

### ISSUE THREAD

**Issue by genghis-tron** [essandess/isp-data-pollution#10]
On Ubuntu 16.04.2 LTS, I get this error after running "python3 isp_data_pollution.py"

Traceback (most recent call last):
  File "isp_data_pollution.py", line 23, in <module>
    import datetime as dt, numpy as np, numpy.random as npr, os, random, requests, signal, tarfile, time
ImportError: No module named 'numpy'

**Comment by essandess** [comment]
You must install the `numpy` Python module. See #9.
