### ISSUE TITLE
Ubuntu 16.04.2 LTS - pip-3.4: command not found

### ISSUE THREAD

**Issue by genghis-tron** [essandess/isp-data-pollution#11]
Still buntu 16LTS issue

"I like pip, so on my machines I would say:
sudo pip-3.4 install numpy requests selenium Faker"

returns:

sudo: pip-3.4: command not found

**Comment by essandess** [comment]
You must install pip version 3. Google Ubuntu install pip version 3. It will be some `apt-get` command.
