### ISSUE TITLE
Error on line 31: module 'os' has no attribute 'nice'

### ISSUE THREAD

**Issue by Exirtis** [essandess/isp-data-pollution#12]
After your instructions with my last issue:
- I downloaded the raw version of `isp_data_pollution.py`
- Ran the script, and got an error about not having the `numpy` module
- But followed the instructions in issue [9](https://github.com/essandess/isp-data-pollution/issues/9) and got `numpy`, `requests`, and `Faker` installed
- Then re-ran the script and got a new error:
```
Traceback (most recent call last):
  File "isp_data_pollution.py", line 31, in <module>
    os.nice(15)
AttributeError: module 'os' has no attribute 'nice'
```
At first I thought I might be missing another dependency, but from your comment on line 30 of the code, it seems that `nice` might be an established Python method or something. So, I'm at a loss.

I hope I'm not being a pain, but... any ideas?

**Comment by essandess** [comment]
Nice sets the process priority on UNIX. You must be on Windows.

I've modified the code to check if nice exists before calling it.

I also checked if there's a Windows equivalent, but it doesn't [appear promising](http://stackoverflow.com/questions/4208/windows-equivalent-of-nice). Someone please pipe up if there's a straightforward way to lower the process priority on Windows.

**Comment by Exirtis** [comment]
Thanks for that. :-)

Regarding lowering process priority on Windows: while I'm not much of a coder I did find a couple of possible solutions ([1](http://stackoverflow.com/questions/1023038/change-process-priority-in-python-cross-platform), [2](http://code.activestate.com/recipes/496767-set-process-priority-in-windows/)) that might be worth looking into; although, I don't know how _straightforward_ they are even if they do work.

Running with the modified script I do get farther in execution, but do I still hit an error further on. I have to go to work now, so I'll open a new issue later when I have time.
