### ISSUE TITLE
Trouble installing on linux mint

### ISSUE THREAD

**Issue by Anonymous343** [essandess/isp-data-pollution#13]
I downloaded the file and installed pip along with all the dependencies. I used the chmod command to allow it to run and this is what I am getting when I run it:

Downloading the blacklist...
done.
Seeding with search for 'maestro'...
Message: Error - Unable to load Atom 'find_elements' from file ':/ghostdriver/./third_party/webdriver-atoms/find_elements.js'

Traceback (most recent call last):
  File "isp_data_pollution.py", line 483, in <module>
    ISPDataPollution(debug=True)
  File "isp_data_pollution.py", line 126, in __init__
    self.pollute_forever()
  File "isp_data_pollution.py", line 211, in pollute_forever
    self.seed_links()
  File "isp_data_pollution.py", line 246, in seed_links
    self.get_websearch(word)
  File "isp_data_pollution.py", line 367, in get_websearch
    if len(self.links) < self.max_links_cached: self.add_url_links(new_links)
  File "isp_data_pollution.py", line 423, in add_url_links
    if self.debug: print('Added {:d} links, {:d} total at url \'{}\'.'.format(k,len(self.links),self.session.current_url))
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 515, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 164, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Error - Unable to load Atom 'execute_script' from file ':/ghostdriver/./third_party/webdriver-atoms/execute_script.js'

Please Help.

Running Linux Mint 18.1

**Comment by essandess** [comment]
See https://github.com/essandess/isp-data-pollution/issues/6#issuecomment-292316026.

There's some issue with phantomjs's `current_url` method on some websites. Watch for the next commit and try after that and let us know if this fixes it for you.

**Comment by Anonymous343** [comment]
Just wondering why my command line output states something about ghostdriver. See message near the top.

**Comment by essandess** [comment]
If it's crawling then it's working. Don't worry about occasional error messages on a few pages.

**Comment by Anonymous343** [comment]
It shows up on every crawl so thats not really occasional. However since you made this program, if thats not a problem then ill take your word.

**Comment by essandess** [comment]
By occasional I mean not every single page download, not every call. This will depend on the phantomjs version installed on your box and where the crawl goes.

If you steadily collect up to the maximum 100k links after a day or so and the script runs without crashing, then it's working.

**Comment by essandess** [comment]
Update to the latest commit. I turned off the exception verbosity unless debug mode is explicitly specified.
