### ISSUE TITLE
" AttributeError: module 'signal' has no attribute 'SIGALRM' "

### ISSUE THREAD

**Issue by Exirtis** [essandess/isp-data-pollution#14]
First, thank you for all of your help thus far. I really appreciate it.

To recap my setup: I'm running Windows 10 with `Python 3.6`, `selenium`, `numpy`, `requests`, `Faker`, and `phantomjs` installed.

After you updated the script to check for the availability of `nice`, I ran the updated script and encountered the following error:
```
Traceback (most recent call last):
  File "isp_data_pollution.py", line 483, in <module>
    ISPDataPollution(debug=True)
  File "isp_data_pollution.py", line 116, in __init__
    signal.signal(signal.SIGALRM, self.phantomjs_hang_handler) # register hang handler
AttributeError: module 'signal' has no attribute 'SIGALRM'
```
I won't even try speculating what's going on here, since I think my prior guesses haven't been very useful.

**Comment by essandess** [comment]
This is a nontrivial problem because I explicitly use this UNIX signal to handle when phantomjs hangs. I was hoping that this got translated to W10 behind the scenes but apparently not.

Would you or someone please Google and suggest Python code to handle timeouts of a hung subprocess on Windows?

**Comment by Exirtis** [comment]
> Would you or someone please Google and suggest Python code to handle timeouts of a hung subprocess on Windows?

I'll look around and see what I can find.
