### ISSUE TITLE
Cannot Install on OS X Because port selenenium is not found

### ISSUE THREAD

**Issue by johnblommers** [essandess/isp-data-pollution#2]
On OS X El Capitan 10.11.6 installing the prerequisites  fails because:

```
sudo port selfupdate
sudo port upgrade outdated
sudo port install selenenium phantomjs
  Error: Port selenenium not found
```
MacPorts is at version 2.4.1 so it's current. The repository has been refreshed. What am I missing?

**Comment by Skeyelab** [comment]
@johnblommers its spelled selenium

**Comment by essandess** [comment]
Thanks, and sorry for the typo folks. But my mistake was worse than that: there's no MacPorts python3 version of selenium yet. Use pip or Anaconda.
