### ISSUE TITLE
Step-by-step guide for Linux-based operating systems

### ISSUE THREAD

**Issue by baimafeima** [essandess/isp-data-pollution#24]
Could you add a step-by-step guide how to get this to work on Linux-based operating systems?

**Comment by randrews01** [comment]
I believe I captured all the steps when I installed this on Ubuntu16.   As follows:


 sudo apt-get install git
  git clone https://github.com/essandess/isp-data-pollution.git
  cd isp-data-pollution/
  sudo apt install python3-pip
  pip3 install --upgrade pip 
  pip3 install numpy
  pip3 install psutil
  sudo -H pip3 install psutil --upgrade
  sudo -H pip3 install --upgrade pip
  sudo -H pip3 install selenium
  sudo -H pip3 install faker
  sudo apt-get install fontconfig
  sudo apt-get install libfontconfig
  sudo apt-get install build-essential chrpath libssl-dev libxft-dev
  sudo apt-get install libfreetype6 libfreetype6-dev
  sudo apt-get install libfontconfig1 libfontconfig1-dev
<download latest version of PhantomJS from their website>
  export PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"
  sudo mv $PHANTOM_JS /usr/local/share
  ls /usr/local/share
  sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
  phantomjs --version
  python3 isp_data_pollution.py

**Comment by essandess** [comment]
Thanks! I'll add this to README.md.
