### ISSUE TITLE
Disable all SSL validation?

### ISSUE THREAD

**Issue by randrews01** [essandess/isp-data-pollution#27]
Hi,

I started researching this topic, and it appears to be a convoluted mess to disable SSL verification with all the different python libraries.  I was wondering if you could give me an option to completely disable SSL validation across the board?  Thanks in advance!

**Comment by essandess** [comment]
I wouldn't recommend disabling TLS for unsupervised web crawls.

That said, the script's creation of the `phantomjs` process exclitly enables TLS, and it would be trivial to turn off checking.

**Comment by randrews01** [comment]
I have my reasons for needing this.  

I have this set but it still doing verification:
driver = webdriver.PhantomJS(desired_capabilities=dcap,service_args=['--disk-cache=false','--ignore-ssl-errors=true','--ssl-protocol=any'])

**Comment by essandess** [comment]
In that case it's a phantomjs issue.

I'd recommend testing with the latest version and failing that, opening a phantomjs issue.

**Comment by randrews01** [comment]
Unfortunately for me, I am using their latest version.  I downloaded it from their site to get this project up and running.  Le sigh.  Oh well :)

**Comment by randrews01** [comment]
By chance, what about calls made with urllib or requests?   Or are those simply handed off to phantomjs?

**Comment by essandess** [comment]
All crawling uses `phantomjs`. All `robots.txt` is handled by `robotparser`, which uses `urllib.request`. See my monkeypatch of their class to specify a UserAgent header in this call.
