### ISSUE TITLE
seed_bias_links question

### ISSUE THREAD

**Issue by MatejKovacic** [essandess/isp-data-pollution#29]
Hi,

I came across this interesting software and have a question.
In seed_bias_links you set some popular websites, which are commonly and regularly used by "averge user"?

If yes, then it would be sensible to add some local popular URL's from my country?

**Comment by essandess** [comment]
Yes, simply replace the URLs in the variable `seed_bias_links` with the ones you want.

It’s easiest to fork the repo and then make your own local edits.
