### ISSUE TITLE
Docker option

### ISSUE THREAD

**Issue by Brandonv101** [essandess/isp-data-pollution#37]
Hi there,

Is it possible to compose the project as a docker container. For example running it inside a CentOS docker container. As when trying to run it within WSL CentOS it does not install due to CentOS showing an error when running the `sudo yum -y install https://centos7.iuscommunity.org/ius-release.rpm`

Thanks

**Comment by dmitryd** [comment]
This project is most likely dead because it is not working with modern python and blacklists are not loading (locations have changed).
