### ISSUE TITLE
invalid syntax on line 7

### ISSUE THREAD

**Issue by Exirtis** [essandess/isp-data-pollution#8]
On running the data pollution script, I get the following error:
```
  File "isp_data_pollution.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```
Here are the install/configuration steps I took (OS = Windows 10):
- Installed Python 3.6
- Installed phantomjs (added to PATH variable, confirmed that it's working by invoking it from command line)
- Installed selenium via pip
- Downloaded isp_data_pollution.py
- Ran `python isp_data_pollution.py` from command line (where I got the error)

It seems like it should be working, but since it's not I must be missing something. Any ideas?

**Comment by essandess** [comment]
You have downloaded a web page—not a python script—then tried to run the web page as a script.

Download the script with a `git clone` command, or direct from GitHub raw: https://raw.githubusercontent.com/essandess/isp-data-pollution/master/isp_data_pollution.py.

**Comment by Exirtis** [comment]
Oh... Duh. It's obviously been too long since I've used GitHub. :-\

Thanks for helping me out!
