### ISSUE TITLE
I'm not smart

### ISSUE THREAD

**Issue by QaptainQualuntium** [essandess/isp-data-pollution#9]
So I'm not very savy when it comes to coding. Hopefully this is helpful to others who feel the same way. Ive downloaded Python 3.6. What do I do from here?

**Comment by essandess** [comment]
You need to install the module dependencies: `numpy`, `requests`, `selenium`, and `Faker`, as well as `phantomjs`. How you do this depends upon your OS.

This involves choosing a Python (v. 3) package manager, typically `pip` or `Anaconda`.

I like `pip`, so on my machines I would say:

```
sudo pip-3.4 install numpy requests selenium Faker
```

I also like MacPorts for native builds, so I might also use:

```
sudo port install py34-numpy py34-requests phantomjs
```

Figure out how to install these libraries on your OS, and the script will run. I'll add these details to the [README](../../README.md).
